services:
  reverse-proxy:
    image: nginx:1.27-alpine
    container_name: reverse-proxy
    ports:
      - "8080:80"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web-server
    networks:
      - test-network

  web-server:
    image: nginx:1.27-alpine
    container_name: web-server
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - test-network

networks:
  test-network:
